app:
  id: ~
  secret: ~
  token: ~

feishu:
  http:
    host: ~
    port: ~

crawl_service:
  host: ~
  port: ~

email:
  from: ~
  to:
    - ~
    - ~
  password: ~
  smtp:
    server: ~
    port: ~
  limit: ~